name: perceiver-io
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=10.2
  - pytorch=1.10
  - torchvision=0.11
  - torchtext=0.11
  - pip
  - pip:
    - pytorch-lightning[extra]~=1.5.0
    - lightning-bolts~=0.4.0
    - torchmetrics~=0.6.0
    - tokenizers
    - einops
